name: Minimal Test

on:
  workflow_dispatch:
  push:
    tags:
      - 'test-v*'

jobs:
  minimal-test:
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Basic info
      run: |
        echo "=== 기본 정보 ==="
        pwd
        ls -la
        echo "=== Python 정보 ==="
        which python3
        python3 --version
        echo "=== 파일 확인 ==="
        ls gui_perfect.py || echo "gui_perfect.py 없음"
        ls .env || echo ".env 없음"

    - name: Setup Python (minimal)
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Test Python only
      run: |
        echo "=== Python 테스트 ==="
        python3 -c "print('Python 작동 확인')"
        python3 -c "import sys; print('Python path:', sys.executable)"

    - name: Test pip only
      run: |
        echo "=== pip 테스트 ==="
        pip --version
        pip install requests
        python3 -c "import requests; print('requests 설치 성공')"

    - name: Create basic file
      run: |
        echo "=== 기본 파일 생성 테스트 ==="
        echo "Hello World" > test.txt
        cat test.txt
        mkdir -p test_dir
        ls -la

    - name: Upload test result
      uses: actions/upload-artifact@v4
      with:
        name: minimal-test-result
        path: test.txt